### ISSUE TITLE
add to awesome-yazi

### ISSUE THREAD

**Issue by AnirudhG07** [dawsers/toggle-view.yazi#1]
Hi, thanks for making your cool amazing plugins.

Would you like to add all your plugins to [awesome-yazi](https://github.com/AnirudhG07/awesome-yazi)? They would be a very nice addition to the list.
Thank you so much!

**Comment by dawsers** [comment]
Thank you for keeping such a cool list, and thank you for [archivemount.yazi](https://github.com/AnirudhG07/archivemount.yazi), from which I borrowed a lot of stuff for [fuse-archive](https://github.com/dawsers/fuse-archive.yazi)!

I submitted a PR https://github.com/AnirudhG07/awesome-yazi/pull/29

**Comment by AnirudhG07** [comment]
No problem. Your dual-pane.yazi is really awesome! I love it
